# Generated by Django 5.2.6 on 2025-09-23 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0014_2_9a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the service', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this service provides')),
                ('icon', models.CharField(default='fa-solid fa-cube', help_text='Font Awesome icon class for this service', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is available for subscription')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in navigation')),
                ('stripe_product', models.ForeignKey(help_text='The Stripe product that grants access to this service', on_delete=django.db.models.deletion.CASCADE, to='djstripe.product')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this access expires (if applicable)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='services.service')),
                ('subscription', models.ForeignKey(blank=True, help_text='The subscription that grants this access', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Service Access',
                'verbose_name_plural': 'User Service Accesses',
                'unique_together': {('user', 'service')},
            },
        ),
    ]
