# Generated by Django 5.2.6 on 2025-09-29 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded data file', upload_to='user_data/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('file_type', models.CharField(help_text='File type (csv, json, xlsx, etc.)', max_length=50)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_log', models.TextField(blank=True, help_text='Log of processing steps and any errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data_files', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Data File',
                'verbose_name_plural': 'User Data Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file', models.FileField(help_text='The processed/cleaned data file', upload_to='processed_data/%Y/%m/%d/')),
                ('summary_data', models.JSONField(default=dict, help_text='Summary statistics and metadata about the processed data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='services.userdatafile')),
            ],
            options={
                'verbose_name': 'User Processed Data',
                'verbose_name_plural': 'User Processed Data',
            },
        ),
    ]
