# Generated by Django 5.2.6 on 2025-10-21 00:29

import apps.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_userdatafile_userprocesseddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatafile',
            name='file',
            field=models.FileField(help_text='The uploaded data file', upload_to=apps.services.models.user_data_file_upload_path),
        ),
        migrations.AlterField(
            model_name='userprocesseddata',
            name='processed_file',
            field=models.FileField(help_text='The processed/cleaned data file', upload_to=apps.services.models.processed_data_file_upload_path),
        ),
    ]
