# Generated by Django 5.2.6 on 2025-11-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_userdatafile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='fa-solid fa-cube', help_text='Font Awesome icon class for this service', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=150, unique=True),
        ),
    ]
