# Generated by Django 5.2.6 on 2025-10-03 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0014_2_9a'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_subscription_available', models.BooleanField(default=False, help_text='When True, shows the Subscribe button for this product. When False, only shows Request Subscription button.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_product', models.ForeignKey(help_text='The Stripe product this availability setting controls', on_delete=django.db.models.deletion.CASCADE, to='djstripe.product')),
            ],
            options={
                'verbose_name': 'Subscription Availability',
                'verbose_name_plural': 'Subscription Availabilities',
                'unique_together': {('stripe_product',)},
            },
        ),
    ]
