# Generated by Django 5.2.6 on 2025-10-03 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0014_2_9a'),
        ('subscriptions', '0002_subscriptionavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscriptionavailability',
            name='user',
            field=models.ForeignKey(blank=True, help_text='If set, this availability applies only to this specific user. If null, applies globally.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionavailability',
            unique_together={('stripe_product', 'user')},
        ),
    ]
