# Generated by Django 5.2.6 on 2025-11-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDemoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the subscription product', max_length=255)),
                ('stripe_product_id', models.CharField(help_text='Stripe Product ID (e.g., prod_T9FO1AD2u8s2xX)', max_length=255, unique=True)),
                ('demo_url', models.URLField(help_text='URL to the demo page or video', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide the demo link on product card')),
                ('button_text', models.CharField(default='View Demo', help_text='Text to display on the demo button', max_length=50)),
                ('open_in_new_tab', models.BooleanField(default=True, help_text='Open demo link in a new browser tab')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Demo Link',
                'verbose_name_plural': 'Product Demo Links',
                'ordering': ['display_order', 'product_name'],
            },
        ),
    ]
