# Generated by Django 5.2.6 on 2025-11-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_productdemolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='request_type',
            field=models.CharField(choices=[('subscription', 'Subscription Request'), ('demo', 'Demo Request')], default='subscription', help_text='Type of request - subscription or demo', max_length=20),
        ),
    ]
