# Generated by Django 5.2.6 on 2025-11-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionrequest_demo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subscription and Demo Request', 'verbose_name_plural': 'Subscription and Demo Requests'},
        ),
    ]
