# Generated by Django 5.2.6 on 2025-11-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text="Font Awesome icon class (e.g., 'fa-route' for route optimization)", max_length=50)),
                ('category', models.CharField(blank=True, help_text="Category like 'Route Planning', 'Accounting', etc.", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Software',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed_software_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='software_tools',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.software'),
        ),
    ]
