# Generated by Django 5.2.6 on 2025-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_software_customuser_completed_software_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_software',
            field=models.TextField(blank=True, help_text='Custom software tools not in the predefined list'),
        ),
    ]
