# Generated by Django 5.2.6 on 2025-11-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_custom_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='category',
            field=models.CharField(blank=True, help_text="Category like 'Route Planning', 'Accounting', etc.", max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='icon',
            field=models.CharField(help_text="Font Awesome icon class (e.g., 'fa-route' for route optimization)", max_length=200),
        ),
    ]
