# Generated by Django 5.2 on 2025-06-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_purchase_product_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfiguration',
            name='content',
            field=models.FileField(blank=True, help_text='Optional file that will be available for download after purchase.', null=True, upload_to='ecommerce/content/'),
        ),
    ]
